long_uptime = false
long_shell = false
long_kernel = true
current_shell = false
physical_cores = true
show = ["Kernel", "Distribution", "WindowManager", "Terminal", "Shell", "Processor", "Memory"]
theme = "gruvbox"
