#!/bin/bash
# vim: ft=bash

fullname=$(getent passwd "$(whoami)" | cut -d ':' -f 5 | cut -d ',' -f 1 | tr -d "\n")
if [ -z "$fullname" ]; then
    echo "$(whoami)@$(hostnamectl | awk 'FNR==1 {print $3}')"
else
    echo "$fullname"
fi
