return {
    opts = {
        ensure_installed = {
            "asm",
            "bash",
            "bitbake",
            "c",
            "cpp",
            "css",
            "dockerfile",
            "ecma",
            "html",
            "html_tags",
            "java",
            "javascript",
            "json",
            "kconfig",
            "lua",
            "make",
            "markdown",
            "markdown_inline",
            "meson",
            "ninja",
            "nix",
            "python",
            "rust",
            "scss",
            "sql",
            "svelte",
            "tcl",
            "toml",
            "typescript",
            "vhdl",
            "vim",
            "vimdoc",
            "xml",
            "yaml",
            "zsh",
        },
        border = "rounded",
        auto_install = true,
        highlight = true,
    }
}
